---
title: "TP 1 Estadística Espacial"
author: "Castillo Zuain"
date: "2026-09-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
###  Lectura del dataset y su estructura

```{r}
# leo el archivo ar_properties 
library(tidyverse) # libreria para data wrangling
datos1a <- read_csv("ar_properties.csv") # Acá completen con su propio PATH al archivo
datos1a # veo la base
```

### Aplicando filtros

Se seleccionan aquellos registros que pertenecen a Argentina y Capital Federal, cuyo precio esta en dolares (USD), el tipo de propiedad corresponde a Departamento y el tipo de operacion sea Venta. 

```{r}
datos1b <- datos1a %>% 
                   # Me quedo con los que pertenecen a Argentina y Capital Federal
            filter(l1 == "Argentina", 
                   l2 == "Capital Federal", 
                   # cuyo precio este en dolares 
                   currency == "USD", 
                   # propiedad tipo Departamento
                   property_type %in% c("Departamento"),
                   # operaciones de venta
                   operation_type == "Venta",
                   # acoto por precio y superficie
                   between(surface_covered,11,500),between(price,1000,2e6)) %>% dplyr::select(id,l3,surface_covered,price,lat,lon,rooms,bathrooms,bedrooms) %>% mutate(pm2=price/surface_covered) %>% rename(precio=price,barrio=l3,sup=surface_covered,ambientes=rooms,baths=bathrooms,cuartos=bedrooms) %>% na.omit()
# chequeo si el filtro se refleja correctamente en mi nuevo dataset datos1b
datos1b 
attach(datos1b) # pongo las variables en memoria
```

Cargo las librerias basicas para trabajar con datos espaciales

```{r}
library(terra)
library(sf)
#vignette(package = "sf")
#vignette("sf1",package = "sf")
library("leaflet")
library(tmap)
library(OpenStreetMap)
```

### Datos Vectoriales

## Cargo deptos como Puntos

```{r}
# transformo el dtaset a sf, con proyeccion EPSG 4326, equivalente a WGS84 latlon
deptos.sf <- datos1b %>% st_as_sf(coords = c("lon", "lat"), crs = 4326)
deptos.sf
class(deptos.sf)
class(deptos.sf$geometry) # sf column
class(deptos.sf$barrio)
# veamos un simple feature (observacion o registro) y un sólo atributo
deptos.sf[1,3]
# plot
plot(deptos.sf[1,3])
# metodos de la clase sf
methods(class = "sf")
# extraigo solo la columna de geometris
st_geometry(deptos.sf)
# Version alternativa usando terra
#lonlat <- cbind(datos1b$lon, datos1b$lat)
#df <- data.frame(ID=datos1b$id, datos1b$sup)
#crdref <- "+proj=longlat +datum=WGS84"
#deptos <- vect(lonlat, atts=df, crs=crdref) # with terra
#deptos.sf <- sf::st_as_sf(deptos) # conversion to sf
#plot(pts)
# grafico del objeto sf
plot(deptos.sf)
# solo el campo l3 (barrio)
plot(deptos.sf[,"barrio"]) # solo el campo l3
# con leaflet
leaflet(deptos.sf) %>% addTiles() %>% addCircleMarkers(radius=0.2)
# with ggplot
ggplot() + geom_sf(data = deptos.sf, size = 0.3)
# con tmap
tmap_mode('view')
qtm(deptos.sf, style = "natural")

```

```{r}
# cargo el shape de calles de CABA
calles.comp <- st_read("C:/Users/anapa/OneDrive/Escritorio/facu/3 año/TRP/callejero-20260902")
calles.comp
# me quedo con algunos features
calles<-calles.comp[,c("id","tipo_c","nom_mapa","long")]
plot(calles)
# selecciono solo las avenidas
avenidas<-calles[calles$tipo_c=="AVENIDA",]
plot(avenidas)
nombres.ave<-avenidas$nom_mapa
# av rivadavia 
cuales<-grep("RIVADAVIA",nombres.ave)
rivadavia<-avenidas[cuales,]
plot(rivadavia)
# largo de la ave rivadavia
sum(rivadavia$long)
# geometria de la ave rivadavia
rivadavia.geo<-rivadavia$geometry
plot(rivadavia.geo)
# grafico con leaflet de avenidas
leaflet(avenidas) %>% addTiles() %>% addPolylines()
# grafico con leaflet de Rivadavia
leaflet(rivadavia) %>% addTiles() %>% addPolylines()

```

```{r}
# cargo barrios

barrios.comp
plot(barrios.comp)
# me quedo solo con feature de barrio
barrios<-barrios.comp[1]
barrios
plot(barrios)
# la geometria
barrios$geometry
class(barrios)
# subseting de poligonos
plot(barrios[1:5,])
print(barrios.comp, n = 3)
# union de barrios
union._barrios<-st_union(barrios)
union._barrios
plot(union._barrios)
# grafico con leaflet barrios
leaflet(barrios) %>% addTiles() %>% addPolygons()
# grafico con leaflet union de barrios
leaflet(union._barrios) %>% addTiles() %>% addPolygons()
```


```{r}
barrios <- st_transform(barrios, 4326)
deptos.sf <- st_transform(deptos.sf, 4326)

pal <- colorFactor(
  palette = "Set3",
  domain = deptos.sf$barrio
)

leaflet() %>%
  addTiles() %>%
  
  addPolygons(
    data = barrios,
    fill = FALSE,
    color = "black",
    weight = 2,
    opacity = 0.8
  ) %>%
  
  addCircleMarkers(
    data = deptos.sf,
    radius = 4,
    color = ~pal(barrio),
    fillColor = ~pal(barrio),
    fillOpacity = 0.7,
    stroke = FALSE,
    popup = ~paste0(
      "<b>Barrio:</b> ", barrio
    )
  
  )
```
```{r}
library(stringi)

# Barrios oficiales
barrios.comp <- st_read("C:/Users/anapa/OneDrive/Escritorio/facu/3 año/TRP/barrios-20260902")
barrios <- barrios.comp

# Asegurar que ambos estén en el mismo CRS
barrios <- st_transform(barrios, 4326)
deptos.sf <- st_transform(deptos.sf, 4326)

# Me quedo con nombre del barrio + geometría
barrios2 <- barrios %>%
  select(BARRIO) %>%
  rename(barrio_real = BARRIO)

comparacion <- st_join(
  deptos.sf,
  barrios2,
  join = st_within,
  left = TRUE
)


comparacion <- comparacion %>%
  mutate(
    barrio_declarado = barrio %>%
      trimws() %>%
      toupper() %>%
      stri_trans_general("Latin-ASCII"),

    barrio_real = barrio_real %>%
      trimws() %>%
      toupper() %>%
      stri_trans_general("Latin-ASCII"),

    correcto = barrio_declarado == barrio_real
  )

# Resultado por barrio
resultado <- comparacion %>%
  st_drop_geometry() %>%
  group_by(barrio_declarado) %>%
  summarise(
    total_puntos = n(),
    puntos_correctos = sum(correcto, na.rm = TRUE),
    puntos_incorrectos = total_puntos - puntos_correctos,
    porcentaje_correcto = round(
      100 * puntos_correctos / total_puntos,
      2
    )
  ) %>%
  arrange(desc(porcentaje_correcto))

resultado
```

